language: go
go:
- 1.7.1
env:
  global:
  - SSH_KEY="travis-key"
  - GIT_NAME="Giuseppe Ragusa"
  - GIT_EMAIL="giuseppe.ragusa@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
install:
- ./scripts/install-hugo.sh
script:
- ./hugo
before_install:
- openssl aes-256-cbc -K $encrypted_79e2e6a9f322_key -iv $encrypted_79e2e6a9f322_iv
  -in travis-key.enc -out travis-key -d
before_script:
- pip install Pygments --user
after_success:
- echo "gragusa.org" > ./public/CNAME
- ./scripts/deploy.sh
