language: go
go:
- 1.7.1
env:
  global:
  - SSH_KEY="travis-key"
  - GIT_NAME="Giuseppe Ragusa"
  - GIT_EMAIL="giuseppe.ragusa@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
- openssl aes-256-cbc -K $encrypted_d3009fa31a8e_key -iv $encrypted_d3009fa31a8e_iv -in travis-key.enc -out travis-key -d
before_script:
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get -u -v github.com/spf13/hugo
- pip install Pygments
script:
- hugo
after_success:
- echo "gragusa.org" > ./public/CNAME
- "./scripts/deploy.sh"
